---
  - name: node & npm installation
    hosts: all
    tasks: 
      - name: apt update
        apt: 
          update_cache: yes 
          cache_valid_time: 3600
      - name: node installation
        apt:
        pkg:
          - nodejs
          - npm
